name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_JSON }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Configure Docker
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: |
          docker build --build-arg GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
                       --build-arg GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
                       --build-arg SECRET=${{ secrets.SECRET }} \
                      -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/fast_gauth:${{ github.sha }} .

      - name: Authenticate Docker to Google Container Registry
        run: gcloud auth configure-docker

      - name: Push Docker image to Google Container Registry
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/fast_gauth:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fast_gauth \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/fast_gauth:${{ github.sha }} \
            --region us-central1 \
            --port 7000 \
            --allow-unauthenticated  \
            --service-account ${{ secrets.GCP_SA_ACCOUNT }}
